.PHONY: clean All

All:
	@echo "----------Building project:[ Constructor - Debug ]----------"
	@cd "Constructor" && "$(MAKE)" -f  "Constructor.mk"
clean:
	@echo "----------Cleaning project:[ Constructor - Debug ]----------"
	@cd "Constructor" && "$(MAKE)" -f  "Constructor.mk" clean
