.PHONY: clean All

All:
	@echo "----------Building project:[ SumofArrayElements - Debug ]----------"
	@cd "SumofArrayElements" && "$(MAKE)" -f  "SumofArrayElements.mk"
clean:
	@echo "----------Cleaning project:[ SumofArrayElements - Debug ]----------"
	@cd "SumofArrayElements" && "$(MAKE)" -f  "SumofArrayElements.mk" clean
