.PHONY: clean All

All:
	@echo "----------Building project:[ ArrayBasics - Debug ]----------"
	@cd "ArrayBasics" && "$(MAKE)" -f  "ArrayBasics.mk"
clean:
	@echo "----------Cleaning project:[ ArrayBasics - Debug ]----------"
	@cd "ArrayBasics" && "$(MAKE)" -f  "ArrayBasics.mk" clean
